### ISSUE TITLE
Updated!

### ISSUE THREAD

**Issue by Seondong** [zhoushengisnoob/DeepClustering#13]
Improving Unsupervised Image Clustering With Robust Learning (arXiv'20) will appear in CVPR'21
Feel free to update accordingly.

**Comment by zhoushengisnoob** [comment]
Congrats!

**Comment by zhoushengisnoob** [comment]
> Improving Unsupervised Image Clustering With Robust Learning (arXiv'20) will appear in CVPR'21
> Feel free to update accordingly.

Congrats! Will you release the code soon? I will update it in my next PR :)

**Comment by Seondong** [comment]
Sure, here is our Github repository. [Link](https://github.com/deu30303/RUC)


Would you like to add our ECCV 2020 paper, "Mitigating Embedding and Class Assignment
Mismatch in Unsupervised Image Classification"?

[PDF](https://www.ecva.net/papers/eccv_2020/papers_ECCV/papers/123690749.pdf)
[Supp](http://www.ecva.net/papers/eccv_2020/papers_ECCV/papers/123690749-supp.pdf)
[Code](https://github.com/dscig/TwoStageUC)
