### ISSUE TITLE
Two important deep clustering papers

### ISSUE THREAD

**Issue by nairouz** [zhoushengisnoob/DeepClustering#15]
Thanks for considering these two papers:

1) Mrabah, Nairouz, et al. "Deep clustering with a Dynamic Autoencoder: From reconstruction towards centroids construction." Neural Networks 130 (2020): 206-228.

2) Mrabah, Nairouz, et al. "Adversarial deep embedded clustering: on a better trade-off between feature randomness and feature drift." IEEE Transactions on Knowledge and Data Engineering (2020).

**Comment by zhoushengisnoob** [comment]
OK，I will update it in the next commit :)
