### ISSUE TITLE
Deep Clustering toolbox

### ISSUE THREAD

**Issue by ShoufaChen** [zhoushengisnoob/DeepClustering#21]
Thanks for your awesome summary @zhoushengisnoob .

Are there any reports that implement multiple algorithms? like `timm` repo in ImageNet classification.

**Comment by zhoushengisnoob** [comment]
Thanks for your suggestion!
Actually the fair comparison and benchmark is already under development :) However, currently we are focusing on the survey paper and the assorted benchmark will (hopefully) be released in the next few months.
Thanks!

**Comment by Hzzone** [comment]
Hi, guys
I have reproduced some common baselines with self-supervised learning for image clustering, see here https://github.com/Hzzone/ProPos.

**Comment by zhoushengisnoob** [comment]
> Hi, guys I have reproduced some common baselines with self-supervised learning for image clustering, see here https://github.com/Hzzone/ProPos.

Looks good! I will update it in the next version
