### ISSUE TITLE
DeepClustering for CFD

### ISSUE THREAD

**Issue by lkampoli** [zhoushengisnoob/DeepClustering#27]
Hello,
thanks for this repository and for the latest paper, very interesting!
I have a question: why, in your opinion, there are not so many applications, if any, of deep clustering, in the fluid dynamic field?

**Comment by zhoushengisnoob** [comment]
Thanks for interest and sorry for the delayed answer.
I think the deep clustering can be widely applied in various fields including the fluid dynamic field. The major difference lies in the representation learning as mentioned in our [paper](https://zhoushengisnoob.github.io/papers/CSUR.pdf). If you have effective way to represent samples in fluid dynamic field, it is highly possible to apply deep clustering.
