### ISSUE TITLE
kernal killed- VaDE Model

### ISSUE THREAD

**Issue by Amalsalem** [zhoushengisnoob/DeepClustering#43]
i have an error in the kernal during runing the VaDE model
i faced this problem before , and i remember because i installed big pkgs.
How can I solve this?  uninstall unneeded pkgs 

![image](https://github.com/zhoushengisnoob/DeepClustering/assets/104210424/69d86f77-86e0-45d1-8799-913e34d37a38)

**Comment by zhoushengisnoob** [comment]
HI, Amalsalem, it seems you are running the official code of VaDE and I suggest you open the issue in the original repo: https://github.com/slim1017/VaDE.
Thanks!
