### ISSUE TITLE
Adding methods

### ISSUE THREAD

**Issue by XifengGuo** [zhoushengisnoob/DeepClustering#5]
Hi, Zhou. Awesome work. Well done.
Some more methods can be added to this list perhaps:
| [Deep Embedded Clustering with Data Augmentation](http://proceedings.mlr.press/v95/guo18b/guo18b.pdf) | DEC-DA | ACML 2018 | [TensorFlow](https://github.com/XifengGuo/DEC-DA) |
| [Adaptive Self-paced Deep Clustering with Data Augmentation](https://ieeexplore.ieee.org/document/8693526) | ASPC-DA | TKDE 2019 | [TensorFlow](https://github.com/XifengGuo/ASPC-DA) |

Additional, for DEC, there is a Keras implementation: https://github.com/XifengGuo/DEC-keras

**Comment by zhoushengisnoob** [comment]
Thanks，Xifeng，I will add them soon:)
